
version: 2.1

jobs:
  build:
    docker:
      win: circleci/windows@2.3.0
    steps:
      - checkout
      - run: mvn build
  tests:
    docker:
      win: circleci/windows@2.3.0
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
      
commands:
  sayhello:
    description: "Any description"
    parameters: 
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>